class TRACKING_STATUS:
    PICKUP = 'PICKUP'
    MID_PICKUP = 'MID_PICKUP'
    MID_DELIVERY = 'MID_DELIVERY'
    DELIVERY = 'DELIVERY'
    STARTING = 'STARTING'

TRACKING_STATUS_CHOICES = (
    ("PICKUP", "PICKUP"),
    ("MID_PICKUP", "MID_PICKUP"),
    ("MID_DELIVERY", "MID_DELIVERY"),
    ("DELIVERY", "DELIVERY"),
    ("STARTING", "STARTING")
)
