# Generated by Django 4.2 on 2023-11-23 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.CharField(default='0.00', max_length=500)),
                ('debt', models.CharField(default='0.00', max_length=500)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latest_booking', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
            ],
        ),
    ]
