# Generated by Django 4.2 on 2023-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='debt',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
