# Generated by Django 4.2 on 2023-10-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_hauls_created_at_alter_locations_created_at'),
        ('accounts', '0004_alter_account_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='latest_booking',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings'),
        ),
    ]
