# Generated by Django 4.2 on 2023-10-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_latest_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
