# Generated by Django 4.2 on 2023-10-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
