# Generated by Django 4.2 on 2023-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_agents_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_kind',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
