# Generated by Django 4.2 on 2023-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_user_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
