# Generated by Django 4.2 on 2023-05-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_agents_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='document',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='truck',
            field=models.CharField(default='', max_length=100),
        ),
    ]
