# Generated by Django 4.2 on 2023-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_drivers_document_alter_drivers_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='profile_img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
