# Generated by Django 4.2 on 2023-07-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_drivers_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pics',
            field=models.CharField(default='', max_length=200),
        ),
    ]
