# Generated by Django 4.2 on 2023-10-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='driving_licence',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='drivers',
            name='insurance_doc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='drivers',
            name='vehicle_doc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
