# Generated by Django 4.2 on 2023-10-05 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_drivers_driving_licence_drivers_insurance_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drivers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
