# Generated by Django 4.2 on 2023-10-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_agents_created_at_agents_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
