# Generated by Django 4.2 on 2023-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_drivers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
