# Generated by Django 4.2 on 2023-10-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_agents_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='special_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
