# Generated by Django 4.2 on 2023-10-07 01:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0011_alter_hauls_created_at_alter_locations_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('tracking_id', models.CharField(default='', max_length=100)),
                ('is_arrived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trackDelivery', to='bookings.locations')),
                ('last_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trackLastLocation', to='bookings.locations')),
                ('pickup_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trackPickup', to='bookings.locations')),
            ],
        ),
    ]
