# Generated by Django 4.2 on 2023-10-07 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_hauls_created_at_alter_locations_created_at'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklocation',
            name='booking',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trackBooking', to='bookings.bookings'),
        ),
    ]
