# Generated by Django 4.2 on 2023-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_tracklocation_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklocation',
            name='at_pickup_location',
            field=models.BooleanField(default=False),
        ),
    ]
