# Generated by Django 4.2 on 2023-10-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tracklocation_at_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracklocation',
            name='at_pickup_location',
        ),
        migrations.AddField(
            model_name='tracklocation',
            name='status',
            field=models.CharField(default='STARTING', max_length=100),
        ),
    ]
