# Generated by Django 4.2 on 2023-10-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_tracklocation_at_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklocation',
            name='is_pickedUp',
            field=models.BooleanField(default=False),
        ),
    ]
