# Generated by Django 4.2 on 2023-07-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(default='', max_length=200)),
                ('truckType', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=500)),
                ('photo_url', models.CharField(default='', max_length=500)),
                ('instruction', models.CharField(default='', max_length=500)),
                ('time', models.CharField(default='', max_length=300)),
                ('distance', models.CharField(default='', max_length=100)),
                ('pickup_price', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hauls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haul', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='delivery_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='bookings.locations'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pickup_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='bookings.locations'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
