# Generated by Django 4.2 on 2023-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_hauls_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauls',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
