# Generated by Django 4.2 on 2023-07-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_hauls_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='load',
            field=models.CharField(default='', max_length=200),
        ),
    ]
