# Generated by Django 4.2 on 2023-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookings_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='mins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
