# Generated by Django 4.2 on 2023-07-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_bookings_time_bookings_hour_bookings_mins'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hauls',
            name='arrival_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hauls',
            name='plate_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hauls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
