# Generated by Django 4.2 on 2023-08-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookings_created_at_bookings_time_hauls_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
