# Generated by Django 4.2 on 2023-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookings_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
