# Generated by Django 4.2 on 2023-10-05 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='pickup_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
