# Generated by Django 4.2 on 2023-10-05 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookings_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hauls',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locations',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
