# Generated by Django 4.2 on 2023-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_bookings_updated_at_hauls_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hauls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
