TRUCK_TYPE = (
    ("MINI_TRUCK", "MINI_TRUCK"),
    ("MIGHTY", "MIGHTY"),
    ("RHINO", "RHINO"),
    ("SEMI_TRAILER_20", "SEMI_TRAILER_20"),
    ("SEMI_TRAILER_30", "SEMI_TRAILER_30"),
    ("FLATBED_20", "FLATBED_20"),
    ("FLATBED_40", "FLATBED_40"),
    ("CONTAINER_20", "CONTAINER_20"),
    ("CONTAINER_40","CONTAINER_40")
)

